repos:
  - repo: local
    hooks:
      - id: npm-format
        name: npm run format
        entry: cd frontend && npm run format
        language: system
        pass_filenames: false
        stages: [commit]
      - id: npm-lint
        name: npm run lint
        entry: cd frontend && npm run lint
        language: system
        pass_filenames: false
        stages: [commit]
      - id: npm-check
        name: npm run check
        entry: cd frontend && npm run check
        language: system
        pass_filenames: false
        stages: [commit]
