services:
  one-click-unbr:
    image: ghcr.io/janlauber/one-click:latest
    ports:
      - "8090:8090"
    environment:
      - LOCAL=true
      - LOCAL_KUBECONFIG_FILE=/home/natroot/one-click/config-unbr.yaml
      # Note: Replace the values from the actual configMap `one-click-config` or provide the env variables directly here
    volumes:
      - one-click-unbr-data:/app/one-click/pb_data
    restart: always

volumes:
  one-click-unbr-data:
