# Project information
site_name: One-Click Deployment
site_author: Jan Lauber
site_description: >-
  Documentation and guides for the One-Click Deployment project.

# Repository
repo_url: https://github.com/janlauber/one-click
repo_name: janlauber/one-click
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2023 Jan Lauber

# Page tree
nav:
  - Home: index.md
  - Research:
    - research/index.md
    - State of Research: research/state-of-research.md
    - Competitive Analysis: research/competitive-analysis.md
    - Requirements: research/requirements.md
    - Use Cases: research/use-cases.md
    - User Stories: research/user-stories.md
    - Personas: research/personas.md
    - Sources: research/sources.md
  - Docs:
    - docs/index.md
    - Architecture: docs/architecture.md
    - Frontend: docs/frontend.md
    - Backend: docs/backend.md
    - Kubernetes Operator: docs/kubernetes-operator.md
    - Scalability: docs/scalability.md
    - Security: docs/security.md
  - Meetings:
    - meetings/index.md
    - 2023-10-23: meetings/2023-10-23.md
  - Decisions:
    - decisions/index.md
    - 0000-template: decisions/0000-template.md
    - 0001-record-architecture-decision: decisions/0001-record-architecture-decision.md
    - 0002-mkdocs-for-documentation: decisions/0002-mkdocs-for-documentation.md
    - 0003-tech-stack: decisions/0003-tech-stack.md
    - 0004-supported-technologies: decisions/0004-supported-technologies.md
    - 0005-use-of-generative-ai: decisions/0005-use-of-generative-ai.md
    - 0006-applications-exclusion: decisions/0006-applications-exclusion.md
    - 0007 Kubernetes Operator: decisions/0007-kubernetes-operator.md
    - 0008 Project Management: decisions/0008-project-management.md
  - Feedback Loop:
    - feedback-loop/index.md
  - About:
    - License: license.md
    - Glossary: glossary.md
    - Project Roadmap: roadmap.md

# Configuration
theme:
  favicon: assets/images/logo/logo_white_circle.png
  logo: assets/images/logo/logo_white_circle.png
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.prune
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Plugins
plugins:
  - search:
      lang: en

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/janlauber
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jan-lauber/



# Markdown extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes