[tool.poetry]
name = "reflex-tests"
version = "0.1.0"
description = ""
authors = ["Jan Lauber <jan.lauber@protonmail.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
reflex = "^0.2.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
