apiVersion: one-click.dev/v1alpha1
kind: Rollout
spec:
  env: []
  horizontalScale:
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  image:
    password: ''
    registry: docker.io
    repository: library/nginx
    tag: latest
    username: ''
  interfaces:
    - name: http
      port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  secrets: []
  serviceAccountName: one-click
  volumes: []
