apiVersion: one-click.dev/v1alpha1
kind: Rollout
metadata:
  name: nginx
  namespace: default
spec:
  env: []
  horizontalScale:
    maxReplicas: 3
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  image:
    registry: docker.io
    repository: library/nginx
    tag: 1.25.3
  interfaces:
    - ingress:
        ingressClass: nginx-external
        rules:
          - host: test32.ch
            path: /
            tls: true
            tlsSecretName: test-cert
      name: http
      port: 80
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi
  secrets: []
  serviceAccountName: one-click
  volumes: []
