apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: one-click-system
resources:
- ns.yaml
- service.yaml
- deployment.yaml
- ingress.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap.yaml
- pvc.yaml
