---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - one-click.io
  resources:
  - frameworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - one-click.io
  resources:
  - frameworks/finalizers
  verbs:
  - update
- apiGroups:
  - one-click.io
  resources:
  - frameworks/status
  verbs:
  - get
  - patch
  - update
