---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - one-click.io
  resources:
  - deployment
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - one-click.io
  resources:
  - deployment/finalizers
  verbs:
  - update
- apiGroups:
  - one-click.io
  resources:
  - deployment/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - one-click.io
  resources:
  - frameworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - one-click.io
  resources:
  - frameworks/finalizers
  verbs:
  - update
- apiGroups:
  - one-click.io
  resources:
  - frameworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - one-click.io
  resources:
  - hpa
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - one-click.io
  resources:
  - hpa/finalizers
  verbs:
  - update
- apiGroups:
  - one-click.io
  resources:
  - hpa/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - one-click.io
  resources:
  - ingress
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - one-click.io
  resources:
  - ingress/finalizers
  verbs:
  - update
- apiGroups:
  - one-click.io
  resources:
  - ingress/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - one-click.io
  resources:
  - persistentvolumeclaim
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - one-click.io
  resources:
  - persistentvolumeclaim/finalizers
  verbs:
  - update
- apiGroups:
  - one-click.io
  resources:
  - persistentvolumeclaim/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - one-click.io
  resources:
  - secret
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - one-click.io
  resources:
  - secret/finalizers
  verbs:
  - update
- apiGroups:
  - one-click.io
  resources:
  - secret/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - one-click.io
  resources:
  - service
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - one-click.io
  resources:
  - service/finalizers
  verbs:
  - update
- apiGroups:
  - one-click.io
  resources:
  - service/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - one-click.io
  resources:
  - serviceaccount
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - one-click.io
  resources:
  - serviceaccount/finalizers
  verbs:
  - update
- apiGroups:
  - one-click.io
  resources:
  - serviceaccount/status
  verbs:
  - get
  - patch
  - update
