# permissions for end users to view rollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rollout-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: rollout-viewer-role
rules:
- apiGroups:
  - one-click.dev
  resources:
  - rollouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - one-click.dev
  resources:
  - rollouts/status
  verbs:
  - get
