apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: one-click-system
spec:
  containers:
  - name: debug-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    volumeMounts:
    - name: one-click-data-volume
      mountPath: /mnt
  volumes:
  - name: one-click-data-volume
    persistentVolumeClaim:
      claimName: one-click-data
