apiVersion: one-click.dev/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/name: rollout
    app.kubernetes.io/instance: rollout-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: rollout-sample
spec:
  image:
    registry: "docker.io"
    repository: "nginx"
    tag: "latest"
  horizontalScale:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  # env:
  #   - name: "REFLEX_USERNAME"
  #     value: "admin32"
  #   - name: DEBUG
  #     value: "true"
  # secrets:
  #   - name: "REFLEX_PASSWORD"
  #     value: "admiin3"
  #   - name: "ANOTHER_SECRET"
  #     value: "122"
  volumes:
    - name: "data2"
      mountPath: "/data"
      size: "2Gi"
      storageClass: "standard"
  #   - name: "data2"
  #     mountPath: "/data2"
  #     size: "2Gi"
  #     storageClass: "standard"
  interfaces:
    - name: "http"
      port: 80
    - name: "https"
      port: 443
      ingress:
        ingressClass: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
        rules:
          - host: "reflex.oneclickapps.dev"
            path: "/test"
            tls: false
          - host: "reflex.oneclickapps.dev"
            path: "/test"
            tls: false
  serviceAccountName: "nginx"
