apiVersion: one-click.dev/v1alpha1
kind: Rollout
metadata:
  name: node-red
  namespace: node-red
spec:
  image:
    registry: "docker.io"
    repository: "nodered/node-red"
    tag: "3.1.1"
  horizontalScale:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  # env:
  #   - name: "REFLEX_USERNAME"
  #     value: "admin"
  #   - name: DEBUG
  #     value: "true"
  # secrets:
  #   - name: "REFLEX_PASSWORD"
  #     value: "admin"
  #   - name: "ANOTHER_SECRET"
  #     value: "122"
  volumes:
    - name: "data"
      mountPath: "/data"
      size: "1Gi"
      storageClass: "standard"
  interfaces:
    - name: "http"
      port: 1880
    # - name: "https"
    #   port: 443
      # ingress:
      #   ingressClass: "nginx"
      #   annotations:
      #     nginx.ingress.kubernetes.io/rewrite-target: /
      #     nginx.ingress.kubernetes.io/ssl-redirect: "false"
      #   rules:
      #     - host: "reflex.oneclickapps.dev"
      #       path: "/test"
      #       tls: false
      #     - host: "reflex.oneclickapps.dev"
      #       path: "/test"
      #       tls: false
    # - name: "https"
    #   port: 8443
    #   ingress:
    #     ingressClass: "nginx"
    #     annotations:
    #       nginx.ingress.kubernetes.io/rewrite-target: /
    #       nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #     rules:
    #       - host: "reflex.oneclickapps.dev"
    #         path: "/"
    #         tls: true
  serviceAccountName: "node-red"
