name: Markdown Link Check

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  linkCheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install markdown-link-check
      run: npm install -g markdown-link-check

    - name: Check links in markdown files
      run: |
        find . -name \*.md -exec markdown-link-check {} \;
